// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserApplication.Context;

namespace UserApplication.Migrations
{
    [DbContext(typeof(UserApplicationDbContext))]
    [Migration("20221109094407_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserApplication.Models.Friend", b =>
                {
                    b.Property<int>("FriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FriendEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GetRegisterUserRegisterId")
                        .HasColumnType("int");

                    b.Property<int>("UserRegisterId")
                        .HasColumnType("int");

                    b.HasKey("FriendId");

                    b.HasIndex("GetRegisterUserRegisterId");

                    b.ToTable("Friend");
                });

            modelBuilder.Entity("UserApplication.Models.Register", b =>
                {
                    b.Property<int>("UserRegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRegisterId");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("UserApplication.Models.Friend", b =>
                {
                    b.HasOne("UserApplication.Models.Register", "GetRegister")
                        .WithMany()
                        .HasForeignKey("GetRegisterUserRegisterId");
                });
#pragma warning restore 612, 618
        }
    }
}
